# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('funds', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_debt', models.BooleanField(db_index=True, default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('wage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('catalog', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
